package com.wantdo.erp.model;

import java.math.BigDecimal;

public class AttributeVariantsItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants_item.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants_item.variantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer variantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants_item.sort
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants_item.variantvalue
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String variantvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants_item.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public AttributeVariantsItem(Integer id, Integer variantid, Integer sort, String variantvalue, BigDecimal price) {
        this.id = id;
        this.variantid = variantid;
        this.sort = sort;
        this.variantvalue = variantvalue;
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public AttributeVariantsItem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants_item.id
     *
     * @return the value of attribute_variants_item.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants_item.id
     *
     * @param id the value for attribute_variants_item.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants_item.variantid
     *
     * @return the value of attribute_variants_item.variantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getVariantid() {
        return variantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants_item.variantid
     *
     * @param variantid the value for attribute_variants_item.variantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVariantid(Integer variantid) {
        this.variantid = variantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants_item.sort
     *
     * @return the value of attribute_variants_item.sort
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants_item.sort
     *
     * @param sort the value for attribute_variants_item.sort
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants_item.variantvalue
     *
     * @return the value of attribute_variants_item.variantvalue
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getVariantvalue() {
        return variantvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants_item.variantvalue
     *
     * @param variantvalue the value for attribute_variants_item.variantvalue
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVariantvalue(String variantvalue) {
        this.variantvalue = variantvalue == null ? null : variantvalue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants_item.price
     *
     * @return the value of attribute_variants_item.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants_item.price
     *
     * @param price the value for attribute_variants_item.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}