package com.wantdo.erp.model;

public class AttributeVariants {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants.sort
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants.variname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String variname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attribute_variants.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public AttributeVariants(Integer id, Integer sort, String variname, String remark) {
        this.id = id;
        this.sort = sort;
        this.variname = variname;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public AttributeVariants() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants.id
     *
     * @return the value of attribute_variants.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants.id
     *
     * @param id the value for attribute_variants.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants.sort
     *
     * @return the value of attribute_variants.sort
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants.sort
     *
     * @param sort the value for attribute_variants.sort
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants.variname
     *
     * @return the value of attribute_variants.variname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getVariname() {
        return variname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants.variname
     *
     * @param variname the value for attribute_variants.variname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVariname(String variname) {
        this.variname = variname == null ? null : variname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attribute_variants.remark
     *
     * @return the value of attribute_variants.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attribute_variants.remark
     *
     * @param remark the value for attribute_variants.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}