package com.wantdo.erp.model;

import java.util.Date;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.custname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String custname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.contact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.sex
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.age
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.idtype
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer idtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.idnumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String idnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.mobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Customer(Integer id, String custname, String contact, Integer sex, Integer age, Integer idtype, String idnumber, String email, String phone, String mobile, String address, Date createon, String ext1, String ext2, String ext3, String remark) {
        this.id = id;
        this.custname = custname;
        this.contact = contact;
        this.sex = sex;
        this.age = age;
        this.idtype = idtype;
        this.idnumber = idnumber;
        this.email = email;
        this.phone = phone;
        this.mobile = mobile;
        this.address = address;
        this.createon = createon;
        this.ext1 = ext1;
        this.ext2 = ext2;
        this.ext3 = ext3;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Customer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.custname
     *
     * @return the value of customer.custname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCustname() {
        return custname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.custname
     *
     * @param custname the value for customer.custname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCustname(String custname) {
        this.custname = custname == null ? null : custname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.contact
     *
     * @return the value of customer.contact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.contact
     *
     * @param contact the value for customer.contact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.sex
     *
     * @return the value of customer.sex
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.sex
     *
     * @param sex the value for customer.sex
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.age
     *
     * @return the value of customer.age
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.age
     *
     * @param age the value for customer.age
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.idtype
     *
     * @return the value of customer.idtype
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getIdtype() {
        return idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.idtype
     *
     * @param idtype the value for customer.idtype
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.idnumber
     *
     * @return the value of customer.idnumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getIdnumber() {
        return idnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.idnumber
     *
     * @param idnumber the value for customer.idnumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setIdnumber(String idnumber) {
        this.idnumber = idnumber == null ? null : idnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.phone
     *
     * @return the value of customer.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.phone
     *
     * @param phone the value for customer.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.mobile
     *
     * @return the value of customer.mobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.mobile
     *
     * @param mobile the value for customer.mobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.createon
     *
     * @return the value of customer.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.createon
     *
     * @param createon the value for customer.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ext1
     *
     * @return the value of customer.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ext1
     *
     * @param ext1 the value for customer.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ext2
     *
     * @return the value of customer.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ext2
     *
     * @param ext2 the value for customer.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.ext3
     *
     * @return the value of customer.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.ext3
     *
     * @param ext3 the value for customer.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.remark
     *
     * @return the value of customer.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.remark
     *
     * @param remark the value for customer.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}