package com.wantdo.erp.model;

public class Model {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.modelname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String modelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column model.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Model(Integer id, String modelname, String url, String ext1, String ext2, String ext3, String remark) {
        this.id = id;
        this.modelname = modelname;
        this.url = url;
        this.ext1 = ext1;
        this.ext2 = ext2;
        this.ext3 = ext3;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table model
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Model() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.id
     *
     * @return the value of model.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.id
     *
     * @param id the value for model.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.modelname
     *
     * @return the value of model.modelname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getModelname() {
        return modelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.modelname
     *
     * @param modelname the value for model.modelname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setModelname(String modelname) {
        this.modelname = modelname == null ? null : modelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.url
     *
     * @return the value of model.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.url
     *
     * @param url the value for model.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.ext1
     *
     * @return the value of model.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.ext1
     *
     * @param ext1 the value for model.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.ext2
     *
     * @return the value of model.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.ext2
     *
     * @param ext2 the value for model.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.ext3
     *
     * @return the value of model.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.ext3
     *
     * @param ext3 the value for model.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column model.remark
     *
     * @return the value of model.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column model.remark
     *
     * @param remark the value for model.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}