package com.wantdo.erp.model;

public class MwsAddress {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.customerName
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String customername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.addressLine1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String addressline1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.addressLine2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String addressline2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.addressLine3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String addressline3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.city
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.county
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.district
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.stateOrRegion
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String stateorregion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.postalCode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String postalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.countryCode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String countrycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_address.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public MwsAddress(Integer id, String customername, String addressline1, String addressline2, String addressline3, String city, String county, String district, String stateorregion, String postalcode, String countrycode, String phone) {
        this.id = id;
        this.customername = customername;
        this.addressline1 = addressline1;
        this.addressline2 = addressline2;
        this.addressline3 = addressline3;
        this.city = city;
        this.county = county;
        this.district = district;
        this.stateorregion = stateorregion;
        this.postalcode = postalcode;
        this.countrycode = countrycode;
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public MwsAddress() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.id
     *
     * @return the value of mws_address.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.id
     *
     * @param id the value for mws_address.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.customerName
     *
     * @return the value of mws_address.customerName
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCustomername() {
        return customername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.customerName
     *
     * @param customername the value for mws_address.customerName
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCustomername(String customername) {
        this.customername = customername == null ? null : customername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.addressLine1
     *
     * @return the value of mws_address.addressLine1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAddressline1() {
        return addressline1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.addressLine1
     *
     * @param addressline1 the value for mws_address.addressLine1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAddressline1(String addressline1) {
        this.addressline1 = addressline1 == null ? null : addressline1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.addressLine2
     *
     * @return the value of mws_address.addressLine2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAddressline2() {
        return addressline2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.addressLine2
     *
     * @param addressline2 the value for mws_address.addressLine2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAddressline2(String addressline2) {
        this.addressline2 = addressline2 == null ? null : addressline2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.addressLine3
     *
     * @return the value of mws_address.addressLine3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAddressline3() {
        return addressline3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.addressLine3
     *
     * @param addressline3 the value for mws_address.addressLine3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAddressline3(String addressline3) {
        this.addressline3 = addressline3 == null ? null : addressline3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.city
     *
     * @return the value of mws_address.city
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.city
     *
     * @param city the value for mws_address.city
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.county
     *
     * @return the value of mws_address.county
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.county
     *
     * @param county the value for mws_address.county
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.district
     *
     * @return the value of mws_address.district
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.district
     *
     * @param district the value for mws_address.district
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.stateOrRegion
     *
     * @return the value of mws_address.stateOrRegion
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getStateorregion() {
        return stateorregion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.stateOrRegion
     *
     * @param stateorregion the value for mws_address.stateOrRegion
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setStateorregion(String stateorregion) {
        this.stateorregion = stateorregion == null ? null : stateorregion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.postalCode
     *
     * @return the value of mws_address.postalCode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPostalcode() {
        return postalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.postalCode
     *
     * @param postalcode the value for mws_address.postalCode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPostalcode(String postalcode) {
        this.postalcode = postalcode == null ? null : postalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.countryCode
     *
     * @return the value of mws_address.countryCode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCountrycode() {
        return countrycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.countryCode
     *
     * @param countrycode the value for mws_address.countryCode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCountrycode(String countrycode) {
        this.countrycode = countrycode == null ? null : countrycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_address.phone
     *
     * @return the value of mws_address.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_address.phone
     *
     * @param phone the value for mws_address.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}