package com.wantdo.erp.model;

public class MwsOrderitem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.mwsorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer mwsorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.asin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String asin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.sellersku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String sellersku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.orderitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String orderitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.title
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.quantityordered
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer quantityordered;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.quantityshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer quantityshipped;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.itemprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String itemprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.shippingprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String shippingprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.giftwrapprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String giftwrapprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.itemtax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String itemtax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.shippingtax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String shippingtax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.giftwraptax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String giftwraptax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.shippingdiscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String shippingdiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.promotiondiscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String promotiondiscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.codfee
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String codfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.codfeediscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String codfeediscount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.giftmessagetext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String giftmessagetext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.giftwraplevel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String giftwraplevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.conditionnote
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String conditionnote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.conditionid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String conditionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.conditionsubtypeid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String conditionsubtypeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.scheduleddeliverystartdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String scheduleddeliverystartdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.scheduleddeliveryenddate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String scheduleddeliveryenddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.pricedesignation
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String pricedesignation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_orderitem.buyercustomizedinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String buyercustomizedinfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public MwsOrderitem(Integer id, Integer mwsorderid, String asin, String sellersku, String orderitemid, String title, Integer quantityordered, Integer quantityshipped, String currency, String itemprice, String shippingprice, String giftwrapprice, String itemtax, String shippingtax, String giftwraptax, String shippingdiscount, String promotiondiscount, String codfee, String codfeediscount, String giftmessagetext, String giftwraplevel, String conditionnote, String conditionid, String conditionsubtypeid, String scheduleddeliverystartdate, String scheduleddeliveryenddate, String pricedesignation, String buyercustomizedinfo) {
        this.id = id;
        this.mwsorderid = mwsorderid;
        this.asin = asin;
        this.sellersku = sellersku;
        this.orderitemid = orderitemid;
        this.title = title;
        this.quantityordered = quantityordered;
        this.quantityshipped = quantityshipped;
        this.currency = currency;
        this.itemprice = itemprice;
        this.shippingprice = shippingprice;
        this.giftwrapprice = giftwrapprice;
        this.itemtax = itemtax;
        this.shippingtax = shippingtax;
        this.giftwraptax = giftwraptax;
        this.shippingdiscount = shippingdiscount;
        this.promotiondiscount = promotiondiscount;
        this.codfee = codfee;
        this.codfeediscount = codfeediscount;
        this.giftmessagetext = giftmessagetext;
        this.giftwraplevel = giftwraplevel;
        this.conditionnote = conditionnote;
        this.conditionid = conditionid;
        this.conditionsubtypeid = conditionsubtypeid;
        this.scheduleddeliverystartdate = scheduleddeliverystartdate;
        this.scheduleddeliveryenddate = scheduleddeliveryenddate;
        this.pricedesignation = pricedesignation;
        this.buyercustomizedinfo = buyercustomizedinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public MwsOrderitem() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.id
     *
     * @return the value of mws_orderitem.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.id
     *
     * @param id the value for mws_orderitem.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.mwsorderid
     *
     * @return the value of mws_orderitem.mwsorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getMwsorderid() {
        return mwsorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.mwsorderid
     *
     * @param mwsorderid the value for mws_orderitem.mwsorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMwsorderid(Integer mwsorderid) {
        this.mwsorderid = mwsorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.asin
     *
     * @return the value of mws_orderitem.asin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAsin() {
        return asin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.asin
     *
     * @param asin the value for mws_orderitem.asin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAsin(String asin) {
        this.asin = asin == null ? null : asin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.sellersku
     *
     * @return the value of mws_orderitem.sellersku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSellersku() {
        return sellersku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.sellersku
     *
     * @param sellersku the value for mws_orderitem.sellersku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSellersku(String sellersku) {
        this.sellersku = sellersku == null ? null : sellersku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.orderitemid
     *
     * @return the value of mws_orderitem.orderitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrderitemid() {
        return orderitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.orderitemid
     *
     * @param orderitemid the value for mws_orderitem.orderitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderitemid(String orderitemid) {
        this.orderitemid = orderitemid == null ? null : orderitemid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.title
     *
     * @return the value of mws_orderitem.title
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.title
     *
     * @param title the value for mws_orderitem.title
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.quantityordered
     *
     * @return the value of mws_orderitem.quantityordered
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getQuantityordered() {
        return quantityordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.quantityordered
     *
     * @param quantityordered the value for mws_orderitem.quantityordered
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setQuantityordered(Integer quantityordered) {
        this.quantityordered = quantityordered;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.quantityshipped
     *
     * @return the value of mws_orderitem.quantityshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getQuantityshipped() {
        return quantityshipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.quantityshipped
     *
     * @param quantityshipped the value for mws_orderitem.quantityshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setQuantityshipped(Integer quantityshipped) {
        this.quantityshipped = quantityshipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.currency
     *
     * @return the value of mws_orderitem.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.currency
     *
     * @param currency the value for mws_orderitem.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.itemprice
     *
     * @return the value of mws_orderitem.itemprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getItemprice() {
        return itemprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.itemprice
     *
     * @param itemprice the value for mws_orderitem.itemprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setItemprice(String itemprice) {
        this.itemprice = itemprice == null ? null : itemprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.shippingprice
     *
     * @return the value of mws_orderitem.shippingprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getShippingprice() {
        return shippingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.shippingprice
     *
     * @param shippingprice the value for mws_orderitem.shippingprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShippingprice(String shippingprice) {
        this.shippingprice = shippingprice == null ? null : shippingprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.giftwrapprice
     *
     * @return the value of mws_orderitem.giftwrapprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getGiftwrapprice() {
        return giftwrapprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.giftwrapprice
     *
     * @param giftwrapprice the value for mws_orderitem.giftwrapprice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setGiftwrapprice(String giftwrapprice) {
        this.giftwrapprice = giftwrapprice == null ? null : giftwrapprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.itemtax
     *
     * @return the value of mws_orderitem.itemtax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getItemtax() {
        return itemtax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.itemtax
     *
     * @param itemtax the value for mws_orderitem.itemtax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setItemtax(String itemtax) {
        this.itemtax = itemtax == null ? null : itemtax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.shippingtax
     *
     * @return the value of mws_orderitem.shippingtax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getShippingtax() {
        return shippingtax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.shippingtax
     *
     * @param shippingtax the value for mws_orderitem.shippingtax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShippingtax(String shippingtax) {
        this.shippingtax = shippingtax == null ? null : shippingtax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.giftwraptax
     *
     * @return the value of mws_orderitem.giftwraptax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getGiftwraptax() {
        return giftwraptax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.giftwraptax
     *
     * @param giftwraptax the value for mws_orderitem.giftwraptax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setGiftwraptax(String giftwraptax) {
        this.giftwraptax = giftwraptax == null ? null : giftwraptax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.shippingdiscount
     *
     * @return the value of mws_orderitem.shippingdiscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getShippingdiscount() {
        return shippingdiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.shippingdiscount
     *
     * @param shippingdiscount the value for mws_orderitem.shippingdiscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShippingdiscount(String shippingdiscount) {
        this.shippingdiscount = shippingdiscount == null ? null : shippingdiscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.promotiondiscount
     *
     * @return the value of mws_orderitem.promotiondiscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPromotiondiscount() {
        return promotiondiscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.promotiondiscount
     *
     * @param promotiondiscount the value for mws_orderitem.promotiondiscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPromotiondiscount(String promotiondiscount) {
        this.promotiondiscount = promotiondiscount == null ? null : promotiondiscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.codfee
     *
     * @return the value of mws_orderitem.codfee
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCodfee() {
        return codfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.codfee
     *
     * @param codfee the value for mws_orderitem.codfee
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCodfee(String codfee) {
        this.codfee = codfee == null ? null : codfee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.codfeediscount
     *
     * @return the value of mws_orderitem.codfeediscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCodfeediscount() {
        return codfeediscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.codfeediscount
     *
     * @param codfeediscount the value for mws_orderitem.codfeediscount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCodfeediscount(String codfeediscount) {
        this.codfeediscount = codfeediscount == null ? null : codfeediscount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.giftmessagetext
     *
     * @return the value of mws_orderitem.giftmessagetext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getGiftmessagetext() {
        return giftmessagetext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.giftmessagetext
     *
     * @param giftmessagetext the value for mws_orderitem.giftmessagetext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setGiftmessagetext(String giftmessagetext) {
        this.giftmessagetext = giftmessagetext == null ? null : giftmessagetext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.giftwraplevel
     *
     * @return the value of mws_orderitem.giftwraplevel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getGiftwraplevel() {
        return giftwraplevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.giftwraplevel
     *
     * @param giftwraplevel the value for mws_orderitem.giftwraplevel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setGiftwraplevel(String giftwraplevel) {
        this.giftwraplevel = giftwraplevel == null ? null : giftwraplevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.conditionnote
     *
     * @return the value of mws_orderitem.conditionnote
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getConditionnote() {
        return conditionnote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.conditionnote
     *
     * @param conditionnote the value for mws_orderitem.conditionnote
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setConditionnote(String conditionnote) {
        this.conditionnote = conditionnote == null ? null : conditionnote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.conditionid
     *
     * @return the value of mws_orderitem.conditionid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getConditionid() {
        return conditionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.conditionid
     *
     * @param conditionid the value for mws_orderitem.conditionid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setConditionid(String conditionid) {
        this.conditionid = conditionid == null ? null : conditionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.conditionsubtypeid
     *
     * @return the value of mws_orderitem.conditionsubtypeid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getConditionsubtypeid() {
        return conditionsubtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.conditionsubtypeid
     *
     * @param conditionsubtypeid the value for mws_orderitem.conditionsubtypeid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setConditionsubtypeid(String conditionsubtypeid) {
        this.conditionsubtypeid = conditionsubtypeid == null ? null : conditionsubtypeid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.scheduleddeliverystartdate
     *
     * @return the value of mws_orderitem.scheduleddeliverystartdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getScheduleddeliverystartdate() {
        return scheduleddeliverystartdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.scheduleddeliverystartdate
     *
     * @param scheduleddeliverystartdate the value for mws_orderitem.scheduleddeliverystartdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setScheduleddeliverystartdate(String scheduleddeliverystartdate) {
        this.scheduleddeliverystartdate = scheduleddeliverystartdate == null ? null : scheduleddeliverystartdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.scheduleddeliveryenddate
     *
     * @return the value of mws_orderitem.scheduleddeliveryenddate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getScheduleddeliveryenddate() {
        return scheduleddeliveryenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.scheduleddeliveryenddate
     *
     * @param scheduleddeliveryenddate the value for mws_orderitem.scheduleddeliveryenddate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setScheduleddeliveryenddate(String scheduleddeliveryenddate) {
        this.scheduleddeliveryenddate = scheduleddeliveryenddate == null ? null : scheduleddeliveryenddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.pricedesignation
     *
     * @return the value of mws_orderitem.pricedesignation
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPricedesignation() {
        return pricedesignation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.pricedesignation
     *
     * @param pricedesignation the value for mws_orderitem.pricedesignation
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPricedesignation(String pricedesignation) {
        this.pricedesignation = pricedesignation == null ? null : pricedesignation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_orderitem.buyercustomizedinfo
     *
     * @return the value of mws_orderitem.buyercustomizedinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getBuyercustomizedinfo() {
        return buyercustomizedinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_orderitem.buyercustomizedinfo
     *
     * @param buyercustomizedinfo the value for mws_orderitem.buyercustomizedinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setBuyercustomizedinfo(String buyercustomizedinfo) {
        this.buyercustomizedinfo = buyercustomizedinfo == null ? null : buyercustomizedinfo.trim();
    }
}