package com.wantdo.erp.model;

import java.util.Date;

public class MwsOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.amazonorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String amazonorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.sellerorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String sellerorderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.purchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.lastupdatedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.orderstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.fulfillmentchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String fulfillmentchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.saleschannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String saleschannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.orderchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String orderchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.shipservicelevel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String shipservicelevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.mwsaddressid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer mwsaddressid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.ordertotal
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ordertotal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.numberofitemsshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer numberofitemsshipped;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.numberofitemsunshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer numberofitemsunshipped;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.paymentmethod
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String paymentmethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.marketplaceid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String marketplaceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.buyeremail
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String buyeremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.buyername
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String buyername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.shipmentservicelevelcategory
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String shipmentservicelevelcategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.shippedbyamazontfm
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Boolean shippedbyamazontfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.tfmshipmentstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String tfmshipmentstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.cbadisplayableshippinglabel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String cbadisplayableshippinglabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.ordertype
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ordertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.earliestshipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date earliestshipdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.latestshipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date latestshipdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.earliestdeliverydate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date earliestdeliverydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.latestdeliverydate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date latestdeliverydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.isbusinessorder
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Boolean isbusinessorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.purchaseordernumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String purchaseordernumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.isprime
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Boolean isprime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.ispremiumorder
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Boolean ispremiumorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mws_order.sellerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String sellerid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public MwsOrder(Integer id, String amazonorderid, String sellerorderid, Date purchasedate, Date lastupdatedate, String orderstatus, String fulfillmentchannel, String saleschannel, String orderchannel, String shipservicelevel, Integer mwsaddressid, String ordertotal, String currency, Integer numberofitemsshipped, Integer numberofitemsunshipped, String paymentmethod, String marketplaceid, String buyeremail, String buyername, String shipmentservicelevelcategory, Boolean shippedbyamazontfm, String tfmshipmentstatus, String cbadisplayableshippinglabel, String ordertype, Date earliestshipdate, Date latestshipdate, Date earliestdeliverydate, Date latestdeliverydate, Boolean isbusinessorder, String purchaseordernumber, Boolean isprime, Boolean ispremiumorder, Date createon, String sellerid) {
        this.id = id;
        this.amazonorderid = amazonorderid;
        this.sellerorderid = sellerorderid;
        this.purchasedate = purchasedate;
        this.lastupdatedate = lastupdatedate;
        this.orderstatus = orderstatus;
        this.fulfillmentchannel = fulfillmentchannel;
        this.saleschannel = saleschannel;
        this.orderchannel = orderchannel;
        this.shipservicelevel = shipservicelevel;
        this.mwsaddressid = mwsaddressid;
        this.ordertotal = ordertotal;
        this.currency = currency;
        this.numberofitemsshipped = numberofitemsshipped;
        this.numberofitemsunshipped = numberofitemsunshipped;
        this.paymentmethod = paymentmethod;
        this.marketplaceid = marketplaceid;
        this.buyeremail = buyeremail;
        this.buyername = buyername;
        this.shipmentservicelevelcategory = shipmentservicelevelcategory;
        this.shippedbyamazontfm = shippedbyamazontfm;
        this.tfmshipmentstatus = tfmshipmentstatus;
        this.cbadisplayableshippinglabel = cbadisplayableshippinglabel;
        this.ordertype = ordertype;
        this.earliestshipdate = earliestshipdate;
        this.latestshipdate = latestshipdate;
        this.earliestdeliverydate = earliestdeliverydate;
        this.latestdeliverydate = latestdeliverydate;
        this.isbusinessorder = isbusinessorder;
        this.purchaseordernumber = purchaseordernumber;
        this.isprime = isprime;
        this.ispremiumorder = ispremiumorder;
        this.createon = createon;
        this.sellerid = sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public MwsOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.id
     *
     * @return the value of mws_order.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.id
     *
     * @param id the value for mws_order.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.amazonorderid
     *
     * @return the value of mws_order.amazonorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAmazonorderid() {
        return amazonorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.amazonorderid
     *
     * @param amazonorderid the value for mws_order.amazonorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAmazonorderid(String amazonorderid) {
        this.amazonorderid = amazonorderid == null ? null : amazonorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.sellerorderid
     *
     * @return the value of mws_order.sellerorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSellerorderid() {
        return sellerorderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.sellerorderid
     *
     * @param sellerorderid the value for mws_order.sellerorderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSellerorderid(String sellerorderid) {
        this.sellerorderid = sellerorderid == null ? null : sellerorderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.purchasedate
     *
     * @return the value of mws_order.purchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.purchasedate
     *
     * @param purchasedate the value for mws_order.purchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.lastupdatedate
     *
     * @return the value of mws_order.lastupdatedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.lastupdatedate
     *
     * @param lastupdatedate the value for mws_order.lastupdatedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLastupdatedate(Date lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.orderstatus
     *
     * @return the value of mws_order.orderstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.orderstatus
     *
     * @param orderstatus the value for mws_order.orderstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderstatus(String orderstatus) {
        this.orderstatus = orderstatus == null ? null : orderstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.fulfillmentchannel
     *
     * @return the value of mws_order.fulfillmentchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getFulfillmentchannel() {
        return fulfillmentchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.fulfillmentchannel
     *
     * @param fulfillmentchannel the value for mws_order.fulfillmentchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setFulfillmentchannel(String fulfillmentchannel) {
        this.fulfillmentchannel = fulfillmentchannel == null ? null : fulfillmentchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.saleschannel
     *
     * @return the value of mws_order.saleschannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSaleschannel() {
        return saleschannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.saleschannel
     *
     * @param saleschannel the value for mws_order.saleschannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSaleschannel(String saleschannel) {
        this.saleschannel = saleschannel == null ? null : saleschannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.orderchannel
     *
     * @return the value of mws_order.orderchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrderchannel() {
        return orderchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.orderchannel
     *
     * @param orderchannel the value for mws_order.orderchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderchannel(String orderchannel) {
        this.orderchannel = orderchannel == null ? null : orderchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.shipservicelevel
     *
     * @return the value of mws_order.shipservicelevel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getShipservicelevel() {
        return shipservicelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.shipservicelevel
     *
     * @param shipservicelevel the value for mws_order.shipservicelevel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShipservicelevel(String shipservicelevel) {
        this.shipservicelevel = shipservicelevel == null ? null : shipservicelevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.mwsaddressid
     *
     * @return the value of mws_order.mwsaddressid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getMwsaddressid() {
        return mwsaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.mwsaddressid
     *
     * @param mwsaddressid the value for mws_order.mwsaddressid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMwsaddressid(Integer mwsaddressid) {
        this.mwsaddressid = mwsaddressid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.ordertotal
     *
     * @return the value of mws_order.ordertotal
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrdertotal() {
        return ordertotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.ordertotal
     *
     * @param ordertotal the value for mws_order.ordertotal
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrdertotal(String ordertotal) {
        this.ordertotal = ordertotal == null ? null : ordertotal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.currency
     *
     * @return the value of mws_order.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.currency
     *
     * @param currency the value for mws_order.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.numberofitemsshipped
     *
     * @return the value of mws_order.numberofitemsshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getNumberofitemsshipped() {
        return numberofitemsshipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.numberofitemsshipped
     *
     * @param numberofitemsshipped the value for mws_order.numberofitemsshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setNumberofitemsshipped(Integer numberofitemsshipped) {
        this.numberofitemsshipped = numberofitemsshipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.numberofitemsunshipped
     *
     * @return the value of mws_order.numberofitemsunshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getNumberofitemsunshipped() {
        return numberofitemsunshipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.numberofitemsunshipped
     *
     * @param numberofitemsunshipped the value for mws_order.numberofitemsunshipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setNumberofitemsunshipped(Integer numberofitemsunshipped) {
        this.numberofitemsunshipped = numberofitemsunshipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.paymentmethod
     *
     * @return the value of mws_order.paymentmethod
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPaymentmethod() {
        return paymentmethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.paymentmethod
     *
     * @param paymentmethod the value for mws_order.paymentmethod
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPaymentmethod(String paymentmethod) {
        this.paymentmethod = paymentmethod == null ? null : paymentmethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.marketplaceid
     *
     * @return the value of mws_order.marketplaceid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getMarketplaceid() {
        return marketplaceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.marketplaceid
     *
     * @param marketplaceid the value for mws_order.marketplaceid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMarketplaceid(String marketplaceid) {
        this.marketplaceid = marketplaceid == null ? null : marketplaceid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.buyeremail
     *
     * @return the value of mws_order.buyeremail
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getBuyeremail() {
        return buyeremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.buyeremail
     *
     * @param buyeremail the value for mws_order.buyeremail
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setBuyeremail(String buyeremail) {
        this.buyeremail = buyeremail == null ? null : buyeremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.buyername
     *
     * @return the value of mws_order.buyername
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getBuyername() {
        return buyername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.buyername
     *
     * @param buyername the value for mws_order.buyername
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setBuyername(String buyername) {
        this.buyername = buyername == null ? null : buyername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.shipmentservicelevelcategory
     *
     * @return the value of mws_order.shipmentservicelevelcategory
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getShipmentservicelevelcategory() {
        return shipmentservicelevelcategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.shipmentservicelevelcategory
     *
     * @param shipmentservicelevelcategory the value for mws_order.shipmentservicelevelcategory
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShipmentservicelevelcategory(String shipmentservicelevelcategory) {
        this.shipmentservicelevelcategory = shipmentservicelevelcategory == null ? null : shipmentservicelevelcategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.shippedbyamazontfm
     *
     * @return the value of mws_order.shippedbyamazontfm
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Boolean getShippedbyamazontfm() {
        return shippedbyamazontfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.shippedbyamazontfm
     *
     * @param shippedbyamazontfm the value for mws_order.shippedbyamazontfm
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShippedbyamazontfm(Boolean shippedbyamazontfm) {
        this.shippedbyamazontfm = shippedbyamazontfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.tfmshipmentstatus
     *
     * @return the value of mws_order.tfmshipmentstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getTfmshipmentstatus() {
        return tfmshipmentstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.tfmshipmentstatus
     *
     * @param tfmshipmentstatus the value for mws_order.tfmshipmentstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTfmshipmentstatus(String tfmshipmentstatus) {
        this.tfmshipmentstatus = tfmshipmentstatus == null ? null : tfmshipmentstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.cbadisplayableshippinglabel
     *
     * @return the value of mws_order.cbadisplayableshippinglabel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCbadisplayableshippinglabel() {
        return cbadisplayableshippinglabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.cbadisplayableshippinglabel
     *
     * @param cbadisplayableshippinglabel the value for mws_order.cbadisplayableshippinglabel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCbadisplayableshippinglabel(String cbadisplayableshippinglabel) {
        this.cbadisplayableshippinglabel = cbadisplayableshippinglabel == null ? null : cbadisplayableshippinglabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.ordertype
     *
     * @return the value of mws_order.ordertype
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrdertype() {
        return ordertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.ordertype
     *
     * @param ordertype the value for mws_order.ordertype
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrdertype(String ordertype) {
        this.ordertype = ordertype == null ? null : ordertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.earliestshipdate
     *
     * @return the value of mws_order.earliestshipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getEarliestshipdate() {
        return earliestshipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.earliestshipdate
     *
     * @param earliestshipdate the value for mws_order.earliestshipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setEarliestshipdate(Date earliestshipdate) {
        this.earliestshipdate = earliestshipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.latestshipdate
     *
     * @return the value of mws_order.latestshipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getLatestshipdate() {
        return latestshipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.latestshipdate
     *
     * @param latestshipdate the value for mws_order.latestshipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLatestshipdate(Date latestshipdate) {
        this.latestshipdate = latestshipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.earliestdeliverydate
     *
     * @return the value of mws_order.earliestdeliverydate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getEarliestdeliverydate() {
        return earliestdeliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.earliestdeliverydate
     *
     * @param earliestdeliverydate the value for mws_order.earliestdeliverydate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setEarliestdeliverydate(Date earliestdeliverydate) {
        this.earliestdeliverydate = earliestdeliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.latestdeliverydate
     *
     * @return the value of mws_order.latestdeliverydate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getLatestdeliverydate() {
        return latestdeliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.latestdeliverydate
     *
     * @param latestdeliverydate the value for mws_order.latestdeliverydate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLatestdeliverydate(Date latestdeliverydate) {
        this.latestdeliverydate = latestdeliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.isbusinessorder
     *
     * @return the value of mws_order.isbusinessorder
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Boolean getIsbusinessorder() {
        return isbusinessorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.isbusinessorder
     *
     * @param isbusinessorder the value for mws_order.isbusinessorder
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setIsbusinessorder(Boolean isbusinessorder) {
        this.isbusinessorder = isbusinessorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.purchaseordernumber
     *
     * @return the value of mws_order.purchaseordernumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPurchaseordernumber() {
        return purchaseordernumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.purchaseordernumber
     *
     * @param purchaseordernumber the value for mws_order.purchaseordernumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPurchaseordernumber(String purchaseordernumber) {
        this.purchaseordernumber = purchaseordernumber == null ? null : purchaseordernumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.isprime
     *
     * @return the value of mws_order.isprime
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Boolean getIsprime() {
        return isprime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.isprime
     *
     * @param isprime the value for mws_order.isprime
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setIsprime(Boolean isprime) {
        this.isprime = isprime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.ispremiumorder
     *
     * @return the value of mws_order.ispremiumorder
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Boolean getIspremiumorder() {
        return ispremiumorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.ispremiumorder
     *
     * @param ispremiumorder the value for mws_order.ispremiumorder
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setIspremiumorder(Boolean ispremiumorder) {
        this.ispremiumorder = ispremiumorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.createon
     *
     * @return the value of mws_order.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.createon
     *
     * @param createon the value for mws_order.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mws_order.sellerid
     *
     * @return the value of mws_order.sellerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mws_order.sellerid
     *
     * @param sellerid the value for mws_order.sellerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid == null ? null : sellerid.trim();
    }
}