package com.wantdo.erp.model;

import java.math.BigDecimal;

public class OrderItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.productitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer productitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.itemsku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String itemsku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.orderitemstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer orderitemstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.description
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.shipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double shipped;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.tax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal tax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.taxcurrency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String taxcurrency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_items.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public OrderItems(Integer id, Integer orderid, Integer productitem, String itemsku, Integer orderitemstatus, String description, Double amount, Double shipped, BigDecimal price, String currency, BigDecimal tax, String taxcurrency, String ext, String remark) {
        this.id = id;
        this.orderid = orderid;
        this.productitem = productitem;
        this.itemsku = itemsku;
        this.orderitemstatus = orderitemstatus;
        this.description = description;
        this.amount = amount;
        this.shipped = shipped;
        this.price = price;
        this.currency = currency;
        this.tax = tax;
        this.taxcurrency = taxcurrency;
        this.ext = ext;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public OrderItems() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.id
     *
     * @return the value of order_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.id
     *
     * @param id the value for order_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.orderid
     *
     * @return the value of order_items.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.orderid
     *
     * @param orderid the value for order_items.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.productitem
     *
     * @return the value of order_items.productitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getProductitem() {
        return productitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.productitem
     *
     * @param productitem the value for order_items.productitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductitem(Integer productitem) {
        this.productitem = productitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.itemsku
     *
     * @return the value of order_items.itemsku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getItemsku() {
        return itemsku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.itemsku
     *
     * @param itemsku the value for order_items.itemsku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setItemsku(String itemsku) {
        this.itemsku = itemsku == null ? null : itemsku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.orderitemstatus
     *
     * @return the value of order_items.orderitemstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOrderitemstatus() {
        return orderitemstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.orderitemstatus
     *
     * @param orderitemstatus the value for order_items.orderitemstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderitemstatus(Integer orderitemstatus) {
        this.orderitemstatus = orderitemstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.description
     *
     * @return the value of order_items.description
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.description
     *
     * @param description the value for order_items.description
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.amount
     *
     * @return the value of order_items.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.amount
     *
     * @param amount the value for order_items.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.shipped
     *
     * @return the value of order_items.shipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getShipped() {
        return shipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.shipped
     *
     * @param shipped the value for order_items.shipped
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShipped(Double shipped) {
        this.shipped = shipped;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.price
     *
     * @return the value of order_items.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.price
     *
     * @param price the value for order_items.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.currency
     *
     * @return the value of order_items.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.currency
     *
     * @param currency the value for order_items.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.tax
     *
     * @return the value of order_items.tax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getTax() {
        return tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.tax
     *
     * @param tax the value for order_items.tax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTax(BigDecimal tax) {
        this.tax = tax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.taxcurrency
     *
     * @return the value of order_items.taxcurrency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getTaxcurrency() {
        return taxcurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.taxcurrency
     *
     * @param taxcurrency the value for order_items.taxcurrency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTaxcurrency(String taxcurrency) {
        this.taxcurrency = taxcurrency == null ? null : taxcurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.ext
     *
     * @return the value of order_items.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.ext
     *
     * @param ext the value for order_items.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_items.remark
     *
     * @return the value of order_items.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_items.remark
     *
     * @param remark the value for order_items.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}