package com.wantdo.erp.model;

import java.util.Date;

public class OrderLogs {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.createby
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.ordercode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.action
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String action;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_logs.message
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String message;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public OrderLogs(Integer id, Integer orderid, Date createon, Integer createby, String ordercode, String action, String message) {
        this.id = id;
        this.orderid = orderid;
        this.createon = createon;
        this.createby = createby;
        this.ordercode = ordercode;
        this.action = action;
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public OrderLogs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.id
     *
     * @return the value of order_logs.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.id
     *
     * @param id the value for order_logs.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.orderid
     *
     * @return the value of order_logs.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.orderid
     *
     * @param orderid the value for order_logs.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.createon
     *
     * @return the value of order_logs.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.createon
     *
     * @param createon the value for order_logs.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.createby
     *
     * @return the value of order_logs.createby
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.createby
     *
     * @param createby the value for order_logs.createby
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.ordercode
     *
     * @return the value of order_logs.ordercode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.ordercode
     *
     * @param ordercode the value for order_logs.ordercode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.action
     *
     * @return the value of order_logs.action
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.action
     *
     * @param action the value for order_logs.action
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_logs.message
     *
     * @return the value of order_logs.message
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_logs.message
     *
     * @param message the value for order_logs.message
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}