package com.wantdo.erp.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ordercode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ordercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer orderstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String internalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String externalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.purchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date purchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.paymentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date paymentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shipmentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date shipmentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.lastupdatetime
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date lastupdatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.fulfillmentchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String fulfillmentchannel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.carrier
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String carrier;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.tracknumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String tracknumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.customer
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String customer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.marketid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String marketid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.sellerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String sellerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.teamid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer teamid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public OrderInfo(Integer id, String ordercode, String type, Integer orderstatus, String internalcode, String externalcode, Date purchasedate, Date paymentdate, Date shipmentdate, Date lastupdatetime, String fulfillmentchannel, String carrier, String tracknumber, String customer, String marketid, BigDecimal amount, String currency, Date createon, String sellerid, Integer teamid, String ext, String remark) {
        this.id = id;
        this.ordercode = ordercode;
        this.type = type;
        this.orderstatus = orderstatus;
        this.internalcode = internalcode;
        this.externalcode = externalcode;
        this.purchasedate = purchasedate;
        this.paymentdate = paymentdate;
        this.shipmentdate = shipmentdate;
        this.lastupdatetime = lastupdatetime;
        this.fulfillmentchannel = fulfillmentchannel;
        this.carrier = carrier;
        this.tracknumber = tracknumber;
        this.customer = customer;
        this.marketid = marketid;
        this.amount = amount;
        this.currency = currency;
        this.createon = createon;
        this.sellerid = sellerid;
        this.teamid = teamid;
        this.ext = ext;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public OrderInfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.id
     *
     * @return the value of order_info.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.id
     *
     * @param id the value for order_info.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ordercode
     *
     * @return the value of order_info.ordercode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ordercode
     *
     * @param ordercode the value for order_info.ordercode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.type
     *
     * @return the value of order_info.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.type
     *
     * @param type the value for order_info.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderstatus
     *
     * @return the value of order_info.orderstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderstatus
     *
     * @param orderstatus the value for order_info.orderstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderstatus(Integer orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.internalcode
     *
     * @return the value of order_info.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getInternalcode() {
        return internalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.internalcode
     *
     * @param internalcode the value for order_info.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setInternalcode(String internalcode) {
        this.internalcode = internalcode == null ? null : internalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.externalcode
     *
     * @return the value of order_info.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExternalcode() {
        return externalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.externalcode
     *
     * @param externalcode the value for order_info.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExternalcode(String externalcode) {
        this.externalcode = externalcode == null ? null : externalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.purchasedate
     *
     * @return the value of order_info.purchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getPurchasedate() {
        return purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.purchasedate
     *
     * @param purchasedate the value for order_info.purchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPurchasedate(Date purchasedate) {
        this.purchasedate = purchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.paymentdate
     *
     * @return the value of order_info.paymentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getPaymentdate() {
        return paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.paymentdate
     *
     * @param paymentdate the value for order_info.paymentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shipmentdate
     *
     * @return the value of order_info.shipmentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getShipmentdate() {
        return shipmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shipmentdate
     *
     * @param shipmentdate the value for order_info.shipmentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShipmentdate(Date shipmentdate) {
        this.shipmentdate = shipmentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.lastupdatetime
     *
     * @return the value of order_info.lastupdatetime
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.lastupdatetime
     *
     * @param lastupdatetime the value for order_info.lastupdatetime
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.fulfillmentchannel
     *
     * @return the value of order_info.fulfillmentchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getFulfillmentchannel() {
        return fulfillmentchannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.fulfillmentchannel
     *
     * @param fulfillmentchannel the value for order_info.fulfillmentchannel
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setFulfillmentchannel(String fulfillmentchannel) {
        this.fulfillmentchannel = fulfillmentchannel == null ? null : fulfillmentchannel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.carrier
     *
     * @return the value of order_info.carrier
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCarrier() {
        return carrier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.carrier
     *
     * @param carrier the value for order_info.carrier
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCarrier(String carrier) {
        this.carrier = carrier == null ? null : carrier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.tracknumber
     *
     * @return the value of order_info.tracknumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getTracknumber() {
        return tracknumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.tracknumber
     *
     * @param tracknumber the value for order_info.tracknumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTracknumber(String tracknumber) {
        this.tracknumber = tracknumber == null ? null : tracknumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.customer
     *
     * @return the value of order_info.customer
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.customer
     *
     * @param customer the value for order_info.customer
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCustomer(String customer) {
        this.customer = customer == null ? null : customer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.marketid
     *
     * @return the value of order_info.marketid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getMarketid() {
        return marketid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.marketid
     *
     * @param marketid the value for order_info.marketid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMarketid(String marketid) {
        this.marketid = marketid == null ? null : marketid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.amount
     *
     * @return the value of order_info.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.amount
     *
     * @param amount the value for order_info.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.currency
     *
     * @return the value of order_info.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.currency
     *
     * @param currency the value for order_info.currency
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.createon
     *
     * @return the value of order_info.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.createon
     *
     * @param createon the value for order_info.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.sellerid
     *
     * @return the value of order_info.sellerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSellerid() {
        return sellerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.sellerid
     *
     * @param sellerid the value for order_info.sellerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSellerid(String sellerid) {
        this.sellerid = sellerid == null ? null : sellerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.teamid
     *
     * @return the value of order_info.teamid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getTeamid() {
        return teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.teamid
     *
     * @param teamid the value for order_info.teamid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTeamid(Integer teamid) {
        this.teamid = teamid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.ext
     *
     * @return the value of order_info.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.ext
     *
     * @param ext the value for order_info.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.remark
     *
     * @return the value of order_info.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.remark
     *
     * @param remark the value for order_info.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}