package com.wantdo.erp.model;

import java.math.BigDecimal;
import java.util.Date;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.objectcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String objectcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.sku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.puname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String puname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.category
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pustatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer pustatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cost
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal cost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.barcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String internalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String externalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.soldable
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer soldable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.purchasedable
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer purchasedable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.volume
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double volume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.weight
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.warranty
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double warranty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.productdesc
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String productdesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date createon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createby
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.owners
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer owners;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Product(Integer id, String objectcode, String sku, String puname, Integer type, String category, Integer pustatus, BigDecimal price, BigDecimal cost, String barcode, String internalcode, String externalcode, Integer soldable, Integer purchasedable, Double volume, Double weight, Double warranty, String productdesc, Date createon, Integer createby, Integer owners, String ext, String remark) {
        this.id = id;
        this.objectcode = objectcode;
        this.sku = sku;
        this.puname = puname;
        this.type = type;
        this.category = category;
        this.pustatus = pustatus;
        this.price = price;
        this.cost = cost;
        this.barcode = barcode;
        this.internalcode = internalcode;
        this.externalcode = externalcode;
        this.soldable = soldable;
        this.purchasedable = purchasedable;
        this.volume = volume;
        this.weight = weight;
        this.warranty = warranty;
        this.productdesc = productdesc;
        this.createon = createon;
        this.createby = createby;
        this.owners = owners;
        this.ext = ext;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Product() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.objectcode
     *
     * @return the value of product.objectcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getObjectcode() {
        return objectcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.objectcode
     *
     * @param objectcode the value for product.objectcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setObjectcode(String objectcode) {
        this.objectcode = objectcode == null ? null : objectcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.sku
     *
     * @return the value of product.sku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.sku
     *
     * @param sku the value for product.sku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.puname
     *
     * @return the value of product.puname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPuname() {
        return puname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.puname
     *
     * @param puname the value for product.puname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPuname(String puname) {
        this.puname = puname == null ? null : puname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.type
     *
     * @return the value of product.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.type
     *
     * @param type the value for product.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.category
     *
     * @return the value of product.category
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.category
     *
     * @param category the value for product.category
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pustatus
     *
     * @return the value of product.pustatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPustatus() {
        return pustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pustatus
     *
     * @param pustatus the value for product.pustatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPustatus(Integer pustatus) {
        this.pustatus = pustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cost
     *
     * @return the value of product.cost
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cost
     *
     * @param cost the value for product.cost
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.barcode
     *
     * @return the value of product.barcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.barcode
     *
     * @param barcode the value for product.barcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.internalcode
     *
     * @return the value of product.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getInternalcode() {
        return internalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.internalcode
     *
     * @param internalcode the value for product.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setInternalcode(String internalcode) {
        this.internalcode = internalcode == null ? null : internalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.externalcode
     *
     * @return the value of product.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExternalcode() {
        return externalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.externalcode
     *
     * @param externalcode the value for product.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExternalcode(String externalcode) {
        this.externalcode = externalcode == null ? null : externalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.soldable
     *
     * @return the value of product.soldable
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSoldable() {
        return soldable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.soldable
     *
     * @param soldable the value for product.soldable
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSoldable(Integer soldable) {
        this.soldable = soldable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.purchasedable
     *
     * @return the value of product.purchasedable
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPurchasedable() {
        return purchasedable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.purchasedable
     *
     * @param purchasedable the value for product.purchasedable
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPurchasedable(Integer purchasedable) {
        this.purchasedable = purchasedable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.volume
     *
     * @return the value of product.volume
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.volume
     *
     * @param volume the value for product.volume
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.weight
     *
     * @return the value of product.weight
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.weight
     *
     * @param weight the value for product.weight
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.warranty
     *
     * @return the value of product.warranty
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getWarranty() {
        return warranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.warranty
     *
     * @param warranty the value for product.warranty
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWarranty(Double warranty) {
        this.warranty = warranty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.productdesc
     *
     * @return the value of product.productdesc
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getProductdesc() {
        return productdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.productdesc
     *
     * @param productdesc the value for product.productdesc
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductdesc(String productdesc) {
        this.productdesc = productdesc == null ? null : productdesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createon
     *
     * @return the value of product.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getCreateon() {
        return createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createon
     *
     * @param createon the value for product.createon
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateon(Date createon) {
        this.createon = createon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createby
     *
     * @return the value of product.createby
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createby
     *
     * @param createby the value for product.createby
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCreateby(Integer createby) {
        this.createby = createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.owners
     *
     * @return the value of product.owners
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOwners() {
        return owners;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.owners
     *
     * @param owners the value for product.owners
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOwners(Integer owners) {
        this.owners = owners;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.ext
     *
     * @return the value of product.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.ext
     *
     * @param ext the value for product.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.remark
     *
     * @return the value of product.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.remark
     *
     * @param remark the value for product.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}