package com.wantdo.erp.model;

import java.math.BigDecimal;

public class ProductItemsSuppliers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items_suppliers.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items_suppliers.productitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer productitem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items_suppliers.supplierid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items_suppliers.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items_suppliers.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductItemsSuppliers(Integer id, Integer productitem, Integer supplierid, String url, BigDecimal price) {
        this.id = id;
        this.productitem = productitem;
        this.supplierid = supplierid;
        this.url = url;
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductItemsSuppliers() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items_suppliers.id
     *
     * @return the value of product_items_suppliers.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items_suppliers.id
     *
     * @param id the value for product_items_suppliers.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items_suppliers.productitem
     *
     * @return the value of product_items_suppliers.productitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getProductitem() {
        return productitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items_suppliers.productitem
     *
     * @param productitem the value for product_items_suppliers.productitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductitem(Integer productitem) {
        this.productitem = productitem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items_suppliers.supplierid
     *
     * @return the value of product_items_suppliers.supplierid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items_suppliers.supplierid
     *
     * @param supplierid the value for product_items_suppliers.supplierid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items_suppliers.url
     *
     * @return the value of product_items_suppliers.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items_suppliers.url
     *
     * @param url the value for product_items_suppliers.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items_suppliers.price
     *
     * @return the value of product_items_suppliers.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items_suppliers.price
     *
     * @param price the value for product_items_suppliers.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}