package com.wantdo.erp.model;

public class ProductVariants {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_variants.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_variants.productid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_variants.variantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer variantid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductVariants(Integer id, Integer productid, Integer variantid) {
        this.id = id;
        this.productid = productid;
        this.variantid = variantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductVariants() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_variants.id
     *
     * @return the value of product_variants.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_variants.id
     *
     * @param id the value for product_variants.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_variants.productid
     *
     * @return the value of product_variants.productid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_variants.productid
     *
     * @param productid the value for product_variants.productid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_variants.variantid
     *
     * @return the value of product_variants.variantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getVariantid() {
        return variantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_variants.variantid
     *
     * @param variantid the value for product_variants.variantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVariantid(Integer variantid) {
        this.variantid = variantid;
    }
}