package com.wantdo.erp.model;

public class ProductVariantsValues {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_variants_values.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_variants_values.productvariantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer productvariantid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_variants_values.variantitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer variantitemid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductVariantsValues(Integer id, Integer productvariantid, Integer variantitemid) {
        this.id = id;
        this.productvariantid = productvariantid;
        this.variantitemid = variantitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductVariantsValues() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_variants_values.id
     *
     * @return the value of product_variants_values.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_variants_values.id
     *
     * @param id the value for product_variants_values.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_variants_values.productvariantid
     *
     * @return the value of product_variants_values.productvariantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getProductvariantid() {
        return productvariantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_variants_values.productvariantid
     *
     * @param productvariantid the value for product_variants_values.productvariantid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductvariantid(Integer productvariantid) {
        this.productvariantid = productvariantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_variants_values.variantitemid
     *
     * @return the value of product_variants_values.variantitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getVariantitemid() {
        return variantitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_variants_values.variantitemid
     *
     * @param variantitemid the value for product_variants_values.variantitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVariantitemid(Integer variantitemid) {
        this.variantitemid = variantitemid;
    }
}