package com.wantdo.erp.model;

import java.math.BigDecimal;

public class ProductItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.productid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer productid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.orderitemcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String orderitemcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.sku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String sku;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.itemname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String itemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.description
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.barcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String barcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String internalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String externalcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.thirdcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String thirdcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.size
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.color
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_items.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductItems(Integer id, Integer productid, String orderitemcode, String sku, String itemname, String description, String barcode, String internalcode, String externalcode, String thirdcode, String size, String color, BigDecimal price) {
        this.id = id;
        this.productid = productid;
        this.orderitemcode = orderitemcode;
        this.sku = sku;
        this.itemname = itemname;
        this.description = description;
        this.barcode = barcode;
        this.internalcode = internalcode;
        this.externalcode = externalcode;
        this.thirdcode = thirdcode;
        this.size = size;
        this.color = color;
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public ProductItems() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.id
     *
     * @return the value of product_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.id
     *
     * @param id the value for product_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.productid
     *
     * @return the value of product_items.productid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getProductid() {
        return productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.productid
     *
     * @param productid the value for product_items.productid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductid(Integer productid) {
        this.productid = productid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.orderitemcode
     *
     * @return the value of product_items.orderitemcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getOrderitemcode() {
        return orderitemcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.orderitemcode
     *
     * @param orderitemcode the value for product_items.orderitemcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderitemcode(String orderitemcode) {
        this.orderitemcode = orderitemcode == null ? null : orderitemcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.sku
     *
     * @return the value of product_items.sku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSku() {
        return sku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.sku
     *
     * @param sku the value for product_items.sku
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSku(String sku) {
        this.sku = sku == null ? null : sku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.itemname
     *
     * @return the value of product_items.itemname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getItemname() {
        return itemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.itemname
     *
     * @param itemname the value for product_items.itemname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setItemname(String itemname) {
        this.itemname = itemname == null ? null : itemname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.description
     *
     * @return the value of product_items.description
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.description
     *
     * @param description the value for product_items.description
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.barcode
     *
     * @return the value of product_items.barcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getBarcode() {
        return barcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.barcode
     *
     * @param barcode the value for product_items.barcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setBarcode(String barcode) {
        this.barcode = barcode == null ? null : barcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.internalcode
     *
     * @return the value of product_items.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getInternalcode() {
        return internalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.internalcode
     *
     * @param internalcode the value for product_items.internalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setInternalcode(String internalcode) {
        this.internalcode = internalcode == null ? null : internalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.externalcode
     *
     * @return the value of product_items.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExternalcode() {
        return externalcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.externalcode
     *
     * @param externalcode the value for product_items.externalcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExternalcode(String externalcode) {
        this.externalcode = externalcode == null ? null : externalcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.thirdcode
     *
     * @return the value of product_items.thirdcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getThirdcode() {
        return thirdcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.thirdcode
     *
     * @param thirdcode the value for product_items.thirdcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setThirdcode(String thirdcode) {
        this.thirdcode = thirdcode == null ? null : thirdcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.size
     *
     * @return the value of product_items.size
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.size
     *
     * @param size the value for product_items.size
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.color
     *
     * @return the value of product_items.color
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.color
     *
     * @param color the value for product_items.color
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setColor(String color) {
        this.color = color == null ? null : color.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_items.price
     *
     * @return the value of product_items.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_items.price
     *
     * @param price the value for product_items.price
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}