package com.wantdo.erp.model;

import java.util.Date;

public class Purchase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.pocode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String pocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.internalid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String internalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.externalid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String externalid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.puchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date puchasedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.paymentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date paymentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.shipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date shipdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.receivedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Date receivedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.invoice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer invoice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.purchasestatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer purchasestatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Purchase(Integer id, String pocode, String internalid, String externalid, Date puchasedate, Date paymentdate, Date shipdate, Date receivedate, Integer invoice, Integer purchasestatus, String remark) {
        this.id = id;
        this.pocode = pocode;
        this.internalid = internalid;
        this.externalid = externalid;
        this.puchasedate = puchasedate;
        this.paymentdate = paymentdate;
        this.shipdate = shipdate;
        this.receivedate = receivedate;
        this.invoice = invoice;
        this.purchasestatus = purchasestatus;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Purchase() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.id
     *
     * @return the value of purchase.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.id
     *
     * @param id the value for purchase.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.pocode
     *
     * @return the value of purchase.pocode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPocode() {
        return pocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.pocode
     *
     * @param pocode the value for purchase.pocode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPocode(String pocode) {
        this.pocode = pocode == null ? null : pocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.internalid
     *
     * @return the value of purchase.internalid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getInternalid() {
        return internalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.internalid
     *
     * @param internalid the value for purchase.internalid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setInternalid(String internalid) {
        this.internalid = internalid == null ? null : internalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.externalid
     *
     * @return the value of purchase.externalid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExternalid() {
        return externalid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.externalid
     *
     * @param externalid the value for purchase.externalid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExternalid(String externalid) {
        this.externalid = externalid == null ? null : externalid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.puchasedate
     *
     * @return the value of purchase.puchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getPuchasedate() {
        return puchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.puchasedate
     *
     * @param puchasedate the value for purchase.puchasedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPuchasedate(Date puchasedate) {
        this.puchasedate = puchasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.paymentdate
     *
     * @return the value of purchase.paymentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getPaymentdate() {
        return paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.paymentdate
     *
     * @param paymentdate the value for purchase.paymentdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.shipdate
     *
     * @return the value of purchase.shipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getShipdate() {
        return shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.shipdate
     *
     * @param shipdate the value for purchase.shipdate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setShipdate(Date shipdate) {
        this.shipdate = shipdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.receivedate
     *
     * @return the value of purchase.receivedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Date getReceivedate() {
        return receivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.receivedate
     *
     * @param receivedate the value for purchase.receivedate
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setReceivedate(Date receivedate) {
        this.receivedate = receivedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.invoice
     *
     * @return the value of purchase.invoice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getInvoice() {
        return invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.invoice
     *
     * @param invoice the value for purchase.invoice
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setInvoice(Integer invoice) {
        this.invoice = invoice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.purchasestatus
     *
     * @return the value of purchase.purchasestatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPurchasestatus() {
        return purchasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.purchasestatus
     *
     * @param purchasestatus the value for purchase.purchasestatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPurchasestatus(Integer purchasestatus) {
        this.purchasestatus = purchasestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.remark
     *
     * @return the value of purchase.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.remark
     *
     * @param remark the value for purchase.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}