package com.wantdo.erp.model;

public class PurchaseOrders {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.purchaseid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer purchaseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer orderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.orderitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer orderitemid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.supplierid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer supplierid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.ponumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ponumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.potracking
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String potracking;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase_orders.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public PurchaseOrders(Integer id, Integer purchaseid, Integer orderid, Integer orderitemid, Integer supplierid, Integer amount, String ponumber, String potracking, String ext, String remark) {
        this.id = id;
        this.purchaseid = purchaseid;
        this.orderid = orderid;
        this.orderitemid = orderitemid;
        this.supplierid = supplierid;
        this.amount = amount;
        this.ponumber = ponumber;
        this.potracking = potracking;
        this.ext = ext;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public PurchaseOrders() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.id
     *
     * @return the value of purchase_orders.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.id
     *
     * @param id the value for purchase_orders.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.purchaseid
     *
     * @return the value of purchase_orders.purchaseid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPurchaseid() {
        return purchaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.purchaseid
     *
     * @param purchaseid the value for purchase_orders.purchaseid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPurchaseid(Integer purchaseid) {
        this.purchaseid = purchaseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.orderid
     *
     * @return the value of purchase_orders.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.orderid
     *
     * @param orderid the value for purchase_orders.orderid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.orderitemid
     *
     * @return the value of purchase_orders.orderitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getOrderitemid() {
        return orderitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.orderitemid
     *
     * @param orderitemid the value for purchase_orders.orderitemid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setOrderitemid(Integer orderitemid) {
        this.orderitemid = orderitemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.supplierid
     *
     * @return the value of purchase_orders.supplierid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.supplierid
     *
     * @param supplierid the value for purchase_orders.supplierid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.amount
     *
     * @return the value of purchase_orders.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.amount
     *
     * @param amount the value for purchase_orders.amount
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.ponumber
     *
     * @return the value of purchase_orders.ponumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPonumber() {
        return ponumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.ponumber
     *
     * @param ponumber the value for purchase_orders.ponumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPonumber(String ponumber) {
        this.ponumber = ponumber == null ? null : ponumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.potracking
     *
     * @return the value of purchase_orders.potracking
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPotracking() {
        return potracking;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.potracking
     *
     * @param potracking the value for purchase_orders.potracking
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPotracking(String potracking) {
        this.potracking = potracking == null ? null : potracking.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.ext
     *
     * @return the value of purchase_orders.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.ext
     *
     * @param ext the value for purchase_orders.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase_orders.remark
     *
     * @return the value of purchase_orders.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase_orders.remark
     *
     * @param remark the value for purchase_orders.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}