package com.wantdo.erp.model;

public class SubscriberModels {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_models.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_models.subscriberid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer subscriberid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_models.modelid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer modelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_models.role
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_models.custid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer custid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column subscriber_models.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public SubscriberModels(Integer id, Integer subscriberid, Integer modelid, Integer role, Integer custid, String remark) {
        this.id = id;
        this.subscriberid = subscriberid;
        this.modelid = modelid;
        this.role = role;
        this.custid = custid;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public SubscriberModels() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_models.id
     *
     * @return the value of subscriber_models.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_models.id
     *
     * @param id the value for subscriber_models.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_models.subscriberid
     *
     * @return the value of subscriber_models.subscriberid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSubscriberid() {
        return subscriberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_models.subscriberid
     *
     * @param subscriberid the value for subscriber_models.subscriberid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSubscriberid(Integer subscriberid) {
        this.subscriberid = subscriberid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_models.modelid
     *
     * @return the value of subscriber_models.modelid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getModelid() {
        return modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_models.modelid
     *
     * @param modelid the value for subscriber_models.modelid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setModelid(Integer modelid) {
        this.modelid = modelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_models.role
     *
     * @return the value of subscriber_models.role
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_models.role
     *
     * @param role the value for subscriber_models.role
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_models.custid
     *
     * @return the value of subscriber_models.custid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_models.custid
     *
     * @param custid the value for subscriber_models.custid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCustid(Integer custid) {
        this.custid = custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column subscriber_models.remark
     *
     * @return the value of subscriber_models.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column subscriber_models.remark
     *
     * @param remark the value for subscriber_models.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}