package com.wantdo.erp.model;

public class Supplier {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String supname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.supstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer supstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String address1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.address2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String address2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.city
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.region
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.country
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.zipcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.contact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.title
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.mobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.fax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.email
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.customerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer customerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supplier.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Supplier(Integer id, String supname, String type, Integer supstatus, String address1, String address2, String city, String region, String country, String zipcode, String contact, String title, String phone, String mobile, String fax, String email, Integer customerid, String url, String remark) {
        this.id = id;
        this.supname = supname;
        this.type = type;
        this.supstatus = supstatus;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.region = region;
        this.country = country;
        this.zipcode = zipcode;
        this.contact = contact;
        this.title = title;
        this.phone = phone;
        this.mobile = mobile;
        this.fax = fax;
        this.email = email;
        this.customerid = customerid;
        this.url = url;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Supplier() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.id
     *
     * @return the value of supplier.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.id
     *
     * @param id the value for supplier.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supname
     *
     * @return the value of supplier.supname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getSupname() {
        return supname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supname
     *
     * @param supname the value for supplier.supname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSupname(String supname) {
        this.supname = supname == null ? null : supname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.type
     *
     * @return the value of supplier.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.type
     *
     * @param type the value for supplier.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.supstatus
     *
     * @return the value of supplier.supstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSupstatus() {
        return supstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.supstatus
     *
     * @param supstatus the value for supplier.supstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSupstatus(Integer supstatus) {
        this.supstatus = supstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address1
     *
     * @return the value of supplier.address1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAddress1() {
        return address1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address1
     *
     * @param address1 the value for supplier.address1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAddress1(String address1) {
        this.address1 = address1 == null ? null : address1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.address2
     *
     * @return the value of supplier.address2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getAddress2() {
        return address2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.address2
     *
     * @param address2 the value for supplier.address2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setAddress2(String address2) {
        this.address2 = address2 == null ? null : address2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.city
     *
     * @return the value of supplier.city
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.city
     *
     * @param city the value for supplier.city
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.region
     *
     * @return the value of supplier.region
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.region
     *
     * @param region the value for supplier.region
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.country
     *
     * @return the value of supplier.country
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.country
     *
     * @param country the value for supplier.country
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.zipcode
     *
     * @return the value of supplier.zipcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.zipcode
     *
     * @param zipcode the value for supplier.zipcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode == null ? null : zipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.contact
     *
     * @return the value of supplier.contact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.contact
     *
     * @param contact the value for supplier.contact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.title
     *
     * @return the value of supplier.title
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.title
     *
     * @param title the value for supplier.title
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.phone
     *
     * @return the value of supplier.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.phone
     *
     * @param phone the value for supplier.phone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.mobile
     *
     * @return the value of supplier.mobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.mobile
     *
     * @param mobile the value for supplier.mobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.fax
     *
     * @return the value of supplier.fax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.fax
     *
     * @param fax the value for supplier.fax
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.email
     *
     * @return the value of supplier.email
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.email
     *
     * @param email the value for supplier.email
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.customerid
     *
     * @return the value of supplier.customerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.customerid
     *
     * @param customerid the value for supplier.customerid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.url
     *
     * @return the value of supplier.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.url
     *
     * @param url the value for supplier.url
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supplier.remark
     *
     * @return the value of supplier.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supplier.remark
     *
     * @param remark the value for supplier.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}