package com.wantdo.erp.model;

public class Sysinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.mark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.version
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysinfo.sysstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer sysstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Sysinfo(Integer id, String mark, String version, Integer sysstatus) {
        this.id = id;
        this.mark = mark;
        this.version = version;
        this.sysstatus = sysstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Sysinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.id
     *
     * @return the value of sysinfo.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.id
     *
     * @param id the value for sysinfo.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.mark
     *
     * @return the value of sysinfo.mark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.mark
     *
     * @param mark the value for sysinfo.mark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.version
     *
     * @return the value of sysinfo.version
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.version
     *
     * @param version the value for sysinfo.version
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVersion(String version) {
        this.version = version == null ? null : version.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysinfo.sysstatus
     *
     * @return the value of sysinfo.sysstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getSysstatus() {
        return sysstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysinfo.sysstatus
     *
     * @param sysstatus the value for sysinfo.sysstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setSysstatus(Integer sysstatus) {
        this.sysstatus = sysstatus;
    }
}