package com.wantdo.erp.model;

public class WarehousePositions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.whid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer whid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.pocode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String pocode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.posistatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer posistatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.x
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double x;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.y
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double y;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.z
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double z;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.lx
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double lx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.ly
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double ly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.lz
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double lz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.rx
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double rx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.ry
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double ry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.rz
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double rz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.volumn
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double volumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.weight
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public WarehousePositions(Integer id, Integer whid, String pocode, Integer type, Integer posistatus, Double x, Double y, Double z, Double lx, Double ly, Double lz, Double rx, Double ry, Double rz, Double volumn, Double weight, String ext, String remark) {
        this.id = id;
        this.whid = whid;
        this.pocode = pocode;
        this.type = type;
        this.posistatus = posistatus;
        this.x = x;
        this.y = y;
        this.z = z;
        this.lx = lx;
        this.ly = ly;
        this.lz = lz;
        this.rx = rx;
        this.ry = ry;
        this.rz = rz;
        this.volumn = volumn;
        this.weight = weight;
        this.ext = ext;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public WarehousePositions() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.id
     *
     * @return the value of warehouse_positions.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.id
     *
     * @param id the value for warehouse_positions.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.whid
     *
     * @return the value of warehouse_positions.whid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getWhid() {
        return whid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.whid
     *
     * @param whid the value for warehouse_positions.whid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhid(Integer whid) {
        this.whid = whid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.pocode
     *
     * @return the value of warehouse_positions.pocode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getPocode() {
        return pocode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.pocode
     *
     * @param pocode the value for warehouse_positions.pocode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPocode(String pocode) {
        this.pocode = pocode == null ? null : pocode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.type
     *
     * @return the value of warehouse_positions.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.type
     *
     * @param type the value for warehouse_positions.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.posistatus
     *
     * @return the value of warehouse_positions.posistatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPosistatus() {
        return posistatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.posistatus
     *
     * @param posistatus the value for warehouse_positions.posistatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPosistatus(Integer posistatus) {
        this.posistatus = posistatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.x
     *
     * @return the value of warehouse_positions.x
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.x
     *
     * @param x the value for warehouse_positions.x
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setX(Double x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.y
     *
     * @return the value of warehouse_positions.y
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.y
     *
     * @param y the value for warehouse_positions.y
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setY(Double y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.z
     *
     * @return the value of warehouse_positions.z
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getZ() {
        return z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.z
     *
     * @param z the value for warehouse_positions.z
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setZ(Double z) {
        this.z = z;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.lx
     *
     * @return the value of warehouse_positions.lx
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.lx
     *
     * @param lx the value for warehouse_positions.lx
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLx(Double lx) {
        this.lx = lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.ly
     *
     * @return the value of warehouse_positions.ly
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getLy() {
        return ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.ly
     *
     * @param ly the value for warehouse_positions.ly
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLy(Double ly) {
        this.ly = ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.lz
     *
     * @return the value of warehouse_positions.lz
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getLz() {
        return lz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.lz
     *
     * @param lz the value for warehouse_positions.lz
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLz(Double lz) {
        this.lz = lz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.rx
     *
     * @return the value of warehouse_positions.rx
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getRx() {
        return rx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.rx
     *
     * @param rx the value for warehouse_positions.rx
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRx(Double rx) {
        this.rx = rx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.ry
     *
     * @return the value of warehouse_positions.ry
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getRy() {
        return ry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.ry
     *
     * @param ry the value for warehouse_positions.ry
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRy(Double ry) {
        this.ry = ry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.rz
     *
     * @return the value of warehouse_positions.rz
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getRz() {
        return rz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.rz
     *
     * @param rz the value for warehouse_positions.rz
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRz(Double rz) {
        this.rz = rz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.volumn
     *
     * @return the value of warehouse_positions.volumn
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getVolumn() {
        return volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.volumn
     *
     * @param volumn the value for warehouse_positions.volumn
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVolumn(Double volumn) {
        this.volumn = volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.weight
     *
     * @return the value of warehouse_positions.weight
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.weight
     *
     * @param weight the value for warehouse_positions.weight
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.ext
     *
     * @return the value of warehouse_positions.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.ext
     *
     * @param ext the value for warehouse_positions.ext
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions.remark
     *
     * @return the value of warehouse_positions.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions.remark
     *
     * @param remark the value for warehouse_positions.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}