package com.wantdo.erp.model;

public class Warehouse {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.whname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String whname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.whaddress
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String whaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.whcontact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String whcontact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.whphone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String whphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.whmobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String whmobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.whmail
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String whmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer positions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.volumn
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double volumn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.longitude
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.latitude
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.stockin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer stockin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.stockout
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer stockout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.stockbigin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer stockbigin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.stockbigout
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer stockbigout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String ext3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse.map
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private byte[] map;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Warehouse(Integer id, String whname, String whaddress, String whcontact, String whphone, String whmobile, String whmail, Integer positions, Double volumn, Double longitude, Double latitude, Integer stockin, Integer stockout, Integer stockbigin, Integer stockbigout, String ext1, String ext2, String ext3, String remark, byte[] map) {
        this.id = id;
        this.whname = whname;
        this.whaddress = whaddress;
        this.whcontact = whcontact;
        this.whphone = whphone;
        this.whmobile = whmobile;
        this.whmail = whmail;
        this.positions = positions;
        this.volumn = volumn;
        this.longitude = longitude;
        this.latitude = latitude;
        this.stockin = stockin;
        this.stockout = stockout;
        this.stockbigin = stockbigin;
        this.stockbigout = stockbigout;
        this.ext1 = ext1;
        this.ext2 = ext2;
        this.ext3 = ext3;
        this.remark = remark;
        this.map = map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Warehouse() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.id
     *
     * @return the value of warehouse.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.id
     *
     * @param id the value for warehouse.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.whname
     *
     * @return the value of warehouse.whname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getWhname() {
        return whname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.whname
     *
     * @param whname the value for warehouse.whname
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhname(String whname) {
        this.whname = whname == null ? null : whname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.whaddress
     *
     * @return the value of warehouse.whaddress
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getWhaddress() {
        return whaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.whaddress
     *
     * @param whaddress the value for warehouse.whaddress
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhaddress(String whaddress) {
        this.whaddress = whaddress == null ? null : whaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.whcontact
     *
     * @return the value of warehouse.whcontact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getWhcontact() {
        return whcontact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.whcontact
     *
     * @param whcontact the value for warehouse.whcontact
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhcontact(String whcontact) {
        this.whcontact = whcontact == null ? null : whcontact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.whphone
     *
     * @return the value of warehouse.whphone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getWhphone() {
        return whphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.whphone
     *
     * @param whphone the value for warehouse.whphone
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhphone(String whphone) {
        this.whphone = whphone == null ? null : whphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.whmobile
     *
     * @return the value of warehouse.whmobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getWhmobile() {
        return whmobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.whmobile
     *
     * @param whmobile the value for warehouse.whmobile
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhmobile(String whmobile) {
        this.whmobile = whmobile == null ? null : whmobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.whmail
     *
     * @return the value of warehouse.whmail
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getWhmail() {
        return whmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.whmail
     *
     * @param whmail the value for warehouse.whmail
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setWhmail(String whmail) {
        this.whmail = whmail == null ? null : whmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.positions
     *
     * @return the value of warehouse.positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPositions() {
        return positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.positions
     *
     * @param positions the value for warehouse.positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPositions(Integer positions) {
        this.positions = positions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.volumn
     *
     * @return the value of warehouse.volumn
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getVolumn() {
        return volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.volumn
     *
     * @param volumn the value for warehouse.volumn
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setVolumn(Double volumn) {
        this.volumn = volumn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.longitude
     *
     * @return the value of warehouse.longitude
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.longitude
     *
     * @param longitude the value for warehouse.longitude
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.latitude
     *
     * @return the value of warehouse.latitude
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.latitude
     *
     * @param latitude the value for warehouse.latitude
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.stockin
     *
     * @return the value of warehouse.stockin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getStockin() {
        return stockin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.stockin
     *
     * @param stockin the value for warehouse.stockin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setStockin(Integer stockin) {
        this.stockin = stockin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.stockout
     *
     * @return the value of warehouse.stockout
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getStockout() {
        return stockout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.stockout
     *
     * @param stockout the value for warehouse.stockout
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setStockout(Integer stockout) {
        this.stockout = stockout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.stockbigin
     *
     * @return the value of warehouse.stockbigin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getStockbigin() {
        return stockbigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.stockbigin
     *
     * @param stockbigin the value for warehouse.stockbigin
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setStockbigin(Integer stockbigin) {
        this.stockbigin = stockbigin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.stockbigout
     *
     * @return the value of warehouse.stockbigout
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getStockbigout() {
        return stockbigout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.stockbigout
     *
     * @param stockbigout the value for warehouse.stockbigout
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setStockbigout(Integer stockbigout) {
        this.stockbigout = stockbigout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.ext1
     *
     * @return the value of warehouse.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.ext1
     *
     * @param ext1 the value for warehouse.ext1
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1 == null ? null : ext1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.ext2
     *
     * @return the value of warehouse.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.ext2
     *
     * @param ext2 the value for warehouse.ext2
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2 == null ? null : ext2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.ext3
     *
     * @return the value of warehouse.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getExt3() {
        return ext3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.ext3
     *
     * @param ext3 the value for warehouse.ext3
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setExt3(String ext3) {
        this.ext3 = ext3 == null ? null : ext3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.remark
     *
     * @return the value of warehouse.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.remark
     *
     * @param remark the value for warehouse.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse.map
     *
     * @return the value of warehouse.map
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public byte[] getMap() {
        return map;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse.map
     *
     * @param map the value for warehouse.map
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setMap(byte[] map) {
        this.map = map;
    }
}