package com.wantdo.erp.model;

public class WarehousePositionsItems {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.positionid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer positionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.productcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String productcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.productnumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Double productnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.positemstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private Integer positemstatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warehouse_positions_items.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public WarehousePositionsItems(Integer id, Integer positionid, String productcode, Double productnumber, String type, Integer positemstatus, String remark) {
        this.id = id;
        this.positionid = positionid;
        this.productcode = productcode;
        this.productnumber = productnumber;
        this.type = type;
        this.positemstatus = positemstatus;
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public WarehousePositionsItems() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.id
     *
     * @return the value of warehouse_positions_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.id
     *
     * @param id the value for warehouse_positions_items.id
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.positionid
     *
     * @return the value of warehouse_positions_items.positionid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPositionid() {
        return positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.positionid
     *
     * @param positionid the value for warehouse_positions_items.positionid
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPositionid(Integer positionid) {
        this.positionid = positionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.productcode
     *
     * @return the value of warehouse_positions_items.productcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getProductcode() {
        return productcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.productcode
     *
     * @param productcode the value for warehouse_positions_items.productcode
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductcode(String productcode) {
        this.productcode = productcode == null ? null : productcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.productnumber
     *
     * @return the value of warehouse_positions_items.productnumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Double getProductnumber() {
        return productnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.productnumber
     *
     * @param productnumber the value for warehouse_positions_items.productnumber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setProductnumber(Double productnumber) {
        this.productnumber = productnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.type
     *
     * @return the value of warehouse_positions_items.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.type
     *
     * @param type the value for warehouse_positions_items.type
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.positemstatus
     *
     * @return the value of warehouse_positions_items.positemstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public Integer getPositemstatus() {
        return positemstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.positemstatus
     *
     * @param positemstatus the value for warehouse_positions_items.positemstatus
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setPositemstatus(Integer positemstatus) {
        this.positemstatus = positemstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warehouse_positions_items.remark
     *
     * @return the value of warehouse_positions_items.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warehouse_positions_items.remark
     *
     * @param remark the value for warehouse_positions_items.remark
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}