package com.wantdo.erp.mapper;

import com.wantdo.erp.model.AccountAttrs;

public interface AccountAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(AccountAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(AccountAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    AccountAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(AccountAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(AccountAttrs record);
}