package com.wantdo.erp.mapper;

import com.wantdo.erp.model.AttributeVariantsItem;

public interface AttributeVariantsItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(AttributeVariantsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(AttributeVariantsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    AttributeVariantsItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(AttributeVariantsItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants_item
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(AttributeVariantsItem record);
}