package com.wantdo.erp.mapper;

import com.wantdo.erp.model.AttributeVariants;

public interface AttributeVariantsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(AttributeVariants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(AttributeVariants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    AttributeVariants selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(AttributeVariants record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attribute_variants
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(AttributeVariants record);
}