package com.wantdo.erp.mapper;

import com.wantdo.erp.model.CustomerAttrs;

public interface CustomerAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(CustomerAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(CustomerAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    CustomerAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(CustomerAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(CustomerAttrs record);
}