package com.wantdo.erp.mapper;

import com.wantdo.erp.model.CustomerModels;

public interface CustomerModelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(CustomerModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(CustomerModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    CustomerModels selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(CustomerModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(CustomerModels record);
}