package com.wantdo.erp.mapper;

import com.wantdo.erp.model.MwsAddress;

public interface MwsAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(MwsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(MwsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    MwsAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(MwsAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_address
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(MwsAddress record);
}