package com.wantdo.erp.mapper;

import com.wantdo.erp.model.MwsOrderitem;

public interface MwsOrderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(MwsOrderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(MwsOrderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    MwsOrderitem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(MwsOrderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_orderitem
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(MwsOrderitem record);
}