package com.wantdo.erp.mapper;

import com.wantdo.erp.model.MwsOrder;

public interface MwsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(MwsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(MwsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    MwsOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(MwsOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mws_order
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(MwsOrder record);
}