package com.wantdo.erp.mapper;

import com.wantdo.erp.model.OrderLogs;

public interface OrderLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(OrderLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(OrderLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    OrderLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(OrderLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_logs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(OrderLogs record);
}