package com.wantdo.erp.mapper;

import com.wantdo.erp.model.OrderAttrs;

public interface OrderAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(OrderAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(OrderAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    OrderAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(OrderAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(OrderAttrs record);
}