package com.wantdo.erp.mapper;

import com.wantdo.erp.model.ProductVariantsValues;

public interface ProductVariantsValuesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(ProductVariantsValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(ProductVariantsValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    ProductVariantsValues selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(ProductVariantsValues record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_variants_values
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(ProductVariantsValues record);
}