package com.wantdo.erp.mapper;

import com.wantdo.erp.model.ProductItemsSuppliers;

public interface ProductItemsSuppliersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(ProductItemsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(ProductItemsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    ProductItemsSuppliers selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(ProductItemsSuppliers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_suppliers
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(ProductItemsSuppliers record);
}