package com.wantdo.erp.mapper;

import com.wantdo.erp.model.ProductItems;

public interface ProductItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(ProductItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(ProductItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    ProductItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(ProductItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(ProductItems record);
}