package com.wantdo.erp.mapper;

import com.wantdo.erp.model.ProductItemsAttrs;

public interface ProductItemsAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(ProductItemsAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(ProductItemsAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    ProductItemsAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(ProductItemsAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_items_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(ProductItemsAttrs record);
}