package com.wantdo.erp.mapper;

import com.wantdo.erp.model.ProductAttrs;

public interface ProductAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(ProductAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(ProductAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    ProductAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(ProductAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(ProductAttrs record);
}