package com.wantdo.erp.mapper;

import com.wantdo.erp.model.PurchaseAttrs;

public interface PurchaseAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(PurchaseAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(PurchaseAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    PurchaseAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(PurchaseAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(PurchaseAttrs record);
}