package com.wantdo.erp.mapper;

import com.wantdo.erp.model.PurchaseOrders;

public interface PurchaseOrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(PurchaseOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(PurchaseOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    PurchaseOrders selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(PurchaseOrders record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table purchase_orders
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(PurchaseOrders record);
}