package com.wantdo.erp.mapper;

import com.wantdo.erp.model.SubscriberAttrs;

public interface SubscriberAttrsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(SubscriberAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(SubscriberAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    SubscriberAttrs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(SubscriberAttrs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_attrs
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(SubscriberAttrs record);
}