package com.wantdo.erp.mapper;

import com.wantdo.erp.model.SubscriberModels;

public interface SubscriberModelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(SubscriberModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(SubscriberModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    SubscriberModels selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(SubscriberModels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber_models
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(SubscriberModels record);
}