package com.wantdo.erp.mapper;

import com.wantdo.erp.model.Subscriber;

public interface SubscriberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(Subscriber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(Subscriber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    Subscriber selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(Subscriber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subscriber
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(Subscriber record);
}