package com.wantdo.erp.mapper;

import com.wantdo.erp.model.Sysinfo;

public interface SysinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    Sysinfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(Sysinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysinfo
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(Sysinfo record);
}