package com.wantdo.erp.mapper;

import com.wantdo.erp.model.WarehousePositions;

public interface WarehousePositionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(WarehousePositions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(WarehousePositions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    WarehousePositions selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(WarehousePositions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(WarehousePositions record);
}