package com.wantdo.erp.mapper;

import com.wantdo.erp.model.WarehousePositionsItems;

public interface WarehousePositionsItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insert(WarehousePositionsItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int insertSelective(WarehousePositionsItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    WarehousePositionsItems selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKeySelective(WarehousePositionsItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warehouse_positions_items
     *
     * @mbggenerated Mon Apr 04 14:25:52 CST 2016
     */
    int updateByPrimaryKey(WarehousePositionsItems record);
}